/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 officeChair.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function OfficeChair(props) {
  const { nodes, materials } = useGLTF("/models/officeChair.gltf");
  return (
    <group {...props} dispose={null} scale={[0.3, 0.3, 0.3]}>
      <mesh
        geometry={nodes.Chair.geometry}
        material={materials.Chair}
        position={[0, 1.243, 0]}
        scale={[0.75, 0.152, 0.75]}
      >
        <mesh
          geometry={nodes.BezierCurve001.geometry}
          material={materials.Metal}
          position={[0, -1.453, -0.231]}
          rotation={[0, 1.544, 0]}
          scale={[0.85, 4.204, 0.85]}
        />
        <mesh
          geometry={nodes.Cube069.geometry}
          material={materials.Chair}
          position={[1.147, 4.909, 0]}
          scale={[0.169, 5.262, 0.914]}
        />
        <group position={[0, -1.021, 0]} scale={[0.234, 0.752, 0.234]}>
          <mesh
            geometry={nodes.Cylinder000.geometry}
            material={materials["Steel Black Polished"]}
          />
          <mesh
            geometry={nodes.Cylinder000_1.geometry}
            material={materials["Steel White"]}
          />
        </group>
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/officeChair.gltf");
